# Generated by Django 3.1.7 on 2021-03-06 14:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('user_id', models.CharField(default=None, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(default='kings', max_length=50)),
                ('last_name', models.CharField(default='kings', max_length=50)),
                ('gender', models.CharField(default='male', max_length=100)),
                ('dob', models.DateField(default=django.utils.timezone.now)),
                ('age', models.IntegerField(default=16)),
                ('place_of_residence', models.CharField(default='isiolo', max_length=50)),
                ('phone_number', models.CharField(default=190, max_length=20)),
                ('email', models.EmailField(default='kongo@gmail.com', max_length=254)),
                ('occupation', models.CharField(default='kings', max_length=20)),
                ('vaccine_name', models.CharField(default='kings', max_length=20)),
                ('date_of_vaccination', models.DateField(default=django.utils.timezone.now)),
                ('comorbidity', models.CharField(default='kings', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vaccinated', models.DateField()),
                ('next_vaccination_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccination_registry.person')),
            ],
        ),
    ]
