# Generated by Django 3.1.6 on 2021-03-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_id', models.CharField(default=None, editable=False, max_length=10, null=True)),
                ('first_name', models.CharField(max_length=200)),
            ],
        ),
    ]
