# Generated by Django 3.1.6 on 2021-03-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination_registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='special_id',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
