# Generated by Django 3.1.7 on 2021-03-06 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination_registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondVaccination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_first_vaccination', models.DateField()),
                ('date_of_second_vaccination', models.DateField()),
                ('effects', models.CharField(default='kings', max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccination_registry.person')),
            ],
        ),
    ]
