# Generated by Django 3.1.7 on 2021-03-06 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination_registry', '0002_secondvaccination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secondvaccination',
            name='user',
        ),
    ]
