# Generated by Django 3.1.7 on 2021-03-06 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination_registry', '0003_remove_secondvaccination_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secondvaccination',
            name='date_of_first_vaccination',
        ),
    ]
