# Generated by Django 3.1.7 on 2021-03-06 20:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination_registry', '0004_remove_secondvaccination_date_of_first_vaccination'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondvaccination',
            name='date_of_first_vaccination',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secondvaccination',
            name='user',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='vaccination_registry.person'),
            preserve_default=False,
        ),
    ]
