# Generated by Django 3.1.6 on 2021-03-05 21:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination_registry', '0006_auto_20210305_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vaccinated', models.DateField()),
                ('next_vaccination_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=16),
        ),
        migrations.AddField(
            model_name='person',
            name='comorbidity',
            field=models.CharField(default='kings', max_length=50),
        ),
        migrations.AddField(
            model_name='person',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(default='kongo@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(default='male', max_length=10),
        ),
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(default='kings', max_length=50),
        ),
        migrations.AddField(
            model_name='person',
            name='occupation',
            field=models.CharField(default='kings', max_length=20),
        ),
        migrations.AddField(
            model_name='person',
            name='phone_number',
            field=models.CharField(default=190, max_length=20),
        ),
        migrations.AddField(
            model_name='person',
            name='place_of_residence',
            field=models.CharField(default='isiolo', max_length=50),
        ),
        migrations.AddField(
            model_name='person',
            name='vaccine_name',
            field=models.CharField(default='kings', max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(default='kings', max_length=50),
        ),
    ]
