# Generated by Django 3.1.7 on 2021-03-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination_registry', '0007_remove_person_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='comorbidity',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(default='Fist', max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(default='Male', max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(default='Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='occupation',
            field=models.CharField(default='Unemplyoyed', max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='place_of_residence',
            field=models.CharField(default='Isiolo', max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='vaccine_name',
            field=models.CharField(default='Pfizer', max_length=20),
        ),
    ]
