# Generated by Django 3.1.7 on 2021-03-07 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccination_registry', '0008_auto_20210307_1314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'persons'},
        ),
    ]
